title: Interior Auto
email: g_cirkova@mail.bg
description: Interior Auto center for leather restoring
destination: docs
twitter_username: GerganaTsirkova
github_username: GerganaTsirkova
destination: docs
# baseurl: ""
baseurl: "/slavi"
url: "/gerganatsirkova.github.io"
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-sitemap
sass:
    style: compressed
defaults:
  #languages
  -
    scope:
      path: ""
    values:
      lang: "bg"
      layout: page
  -
    scope:
      path: "en"
    values:
      lang: "en"
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs]

