title: interior Auto
email: interiorauto@abv.bg
description: Interior auto - car interior restoration
destination: docs
<<<<<<< HEAD
url: "https://interiorauto.eu"
=======
github_username: GerganaTsirkova
destination: docs
# url: "https://github.com/GerganaTsirkova/interiorauto"
url: ""
>>>>>>> f6955fbe514d41ed110e2b81f0ae57e72a576561
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-sitemap
sass:
    style: compressed
defaults:
  -
    scope:
      path: ""
    values:
      lang: "bg"
      layout: page
  -
    scope:
      path: "en"
    values:
      lang: "en"
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs,LICENCE.txt, LICENCE-images.txt]

