title: interior Auto
email: www.interiorauto.bg
description: interior Auto center for leather restoring
destination: docs
twitter_username: GerganaTsirkova
github_username: GerganaTsirkova
destination: docs
# baseurl: ""
baseurl: "/slavi"
url: "https://gerganatsirkova.github.io/slavi/"
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-sitemap
sass:
    style: compressed
defaults:
  #languages
  -
    scope:
      path: ""
    values:
      lang: "bg"
      layout: page
  -
    scope:
      path: "en"
    values:
      lang: "en"
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs,LICENCE.txt, LICENCE-images.txt]

