title: Leather Restore & Clean Centre - Ruse
email: g_cirkova@mail.bg
description: Car leather repair!
destination: docs
twitter_username: GerganaTsirkova
github_username: GerganaTsirkova
destination: docs
# baseurl: ""
baseurl: "/slavi"
url: ""
markdown: kramdown
plugins:
    - jekyll-feed
sass:
    style: compressed
defaults:
  #languages
  -
    scope:
      path: "."
    values:
      lang: "bg"
      layout: page
  -
    scope:
      path: "en"
    values:
      lang: "en"
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs]

